### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by bruennlein** [anandtrex/collabdraw#7]
When I walk through the instructions, the installation fails at step: pip install -r requirements.txt
I´ve tried this with Ubuntu 16.04 and Debian Jessie.

(venv) root@whiteboard:~/collabdraw# pip install -r requirements.txt
Collecting git+http://anongit.freedesktop.org/git/pycairo (from -r requirements.txt (line 6))
  Cloning http://anongit.freedesktop.org/git/pycairo to /tmp/pip-suwlbwj5-build
Collecting decorator==3.4.0 (from -r requirements.txt (line 1))
  Downloading decorator-3.4.0.tar.gz
Collecting pystacia==0.1 (from -r requirements.txt (line 2))
  Downloading pystacia-0.1.tar.gz
Collecting redis==2.7.2 (from -r requirements.txt (line 3))
  Downloading redis-2.7.2.tar.gz (50kB)
    100% |################################| 51kB 3.5MB/s
Collecting six==1.2.0 (from -r requirements.txt (line 4))
  Downloading six-1.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/root/collabdraw/venv/lib/python3.4/site-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/root/collabdraw/venv/lib/python3.4/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/root/collabdraw/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 49, in <module>
        from six.moves import urllib, map, filter
    ImportError: cannot import name 'urllib'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ql40ch35/six/
(venv) root@whiteboard:~/collabdraw#

**Comment by anandtrex** [comment]
Hi @bruennlein The install instructions are very old, and they probably don't work anymore. I'm not currently maintaining this project, or plan to do so anytime soon. I'll gladly accept pull requests though, if you are so inclined.

**Comment by bruennlein** [comment]
Hi @anandtrex 
Thats very sad. I would really like to do so, but I don´t know how. I´ve already tried to fix the install but I was completely unsuccessful and had to give up.
This is very sad because this project seems to be very useful.

Cheers...
